### PR TITLE
use NDEBUG instead of DEBUG in preprocessor directives

### PR DESCRIPTION
**Pull request by nychiang**
use `#ifndef NDEBUG` instead of `#ifdef DEBUG`

### CODE REVIEW

**Comment by ashermancinelli** [comment]
Looks like github ci found an error:
```
src/LinAlg/hiopVectorPar.cpp:221:2: error: invalid preprocessing directive #infdef; did you mean #ifdef?
```

**Comment by nychiang** [comment]
@ashermancinelli Yes, I noticed the CI result and I have already fixed it in my next commit. In the meantime I found another problem in CMake, which I will file a new issue soon.

**Comment by ashermancinelli** [comment]
Just to clarify, when are we using `NDEBUG` vs `HIOP_DEEPCHECKS`?

**Comment by cnpetra** [comment]
> Just to clarify, when are we using `NDEBUG` vs `HIOP_DEEPCHECKS`?

it' about a fixing an inconsistency in hiop re: assert and DEBUG. `assert` is based on NDEBUG, while hiop in many cases uses `assert` inside `ifdef DEBUG`. This inconsistency can result in compilation errors or asserts being disabled in debug mode. The latter happens for example when NDEBUG not defined and also DEBUG not defined, which is a valid "debug" configuration as far as I remember.

**Comment by cnpetra** [comment]
@nychiang is this ready to review / merge ?

**Comment by nychiang** [comment]
@cnpetra  yes, it is ready. just need your quick review and approval

**Pull request merged**
