### PR TITLE
Adding version info struct

### PR DESCRIPTION
**Pull request by ashermancinelli**
As per our offline discussion @cnpetra. I think a method like `void dumpVersionInfo()` would be nice to print out as well.

### CODE REVIEW

**Comment by ashermancinelli** [comment]
@cnpetra from our conversation offline:

```cpp
#include <hiopVersion.hpp>
using namespace hiop;
int main()
{
  printf("%s\n", hiopVersion::version().c_str());
  int a,b,c;
  hiopVersion::version(a,b,c);
  printf("Got version %d.%d.%d\n",a,b,c);
  printf("Got release date: %s\n",hiopVersion::releaseDate().c_str());
  printf("%s", hiopVersion::fullVersionInfo().c_str());
}
```
Yields:
```shell
0.3.0
Got version 0.3.0
Got release date: 2020-12-09
HiOp 0.3.0 2020-12-09
Built with:
GPU: NO
MPI: YES
MAGMA: NO
RAJA: NO
Sparse: NO
COINHSL: NO
STRUMPACK: NO
```
Anything else you'd like to add? You mentioned hiopInterface including hiopVersion, just checking for confirmation.

**Comment by ashermancinelli** [comment]
cc @pelesh

**Comment by pelesh** [comment]
How do you set `HIOP_VERSION_MAJOR`, etc. in `hiop_defs.hpp`?

**Comment by ashermancinelli** [comment]
> How do you set `HIOP_VERSION_MAJOR`, etc. in `hiop_defs.hpp`?

CMake deduces it from the line `project(hiop VERSION "0.3.0")`

**Comment by ashermancinelli** [comment]
@cnpetra I believe this is ready for merge unless you'd like anything else changed

**Comment by cnpetra** [comment]
lgtm

**Pull request merged**
