### PR TITLE
Update ci dependencies

### PR DESCRIPTION
**Pull request by ashermancinelli**
CI dependencies switched to modules to improve flexibility when building new versions of dependencies.

### CODE REVIEW

**Review by CameronRutherford — APPROVED** [review]
The respective spack environments on our clusters are still useful, but I think using this module based approach is the best path forward. +1 to documenting the dependencies in this repo as the modules + comments are clearer than a spack environment name.

**Comment by cnpetra** [comment]
@ashermancinelli the latest commit does not pass the ORNL CI, could you please take a look?

**Review by cnpetra — APPROVED** [review]
lgtm, will merge once it passes the ornl ci

**Comment by ashermancinelli** [comment]
Our CI runners were down on ascent, I assume for training or something, but passed when I ran by hand. I'll rerun and merge when it passes.

**Comment by ashermancinelli** [comment]
@cnpetra This is passing on ORNL now that pipelines have been restored there.

**Comment by nychiang** [comment]
Thanks a lot Asher. @ashermancinelli 
I failed to compile hiop on ascent due to some dependency issue, and your fix in this PR helps a lot.
Cheers,

**Pull request merged**
