### PR TITLE
Options for building shared and static library

### PR DESCRIPTION
**Pull request by ashermancinelli**
Builds shared lib as in #26 with options for shared and static.

### CODE REVIEW

**Comment by cnpetra** [comment]
Everything under `plan\` is supposed to be private-ish ;)

**Comment by cnpetra** [comment]
since this PR addresses build system issues, on my mac this line in `CMakeLists.txt`
```
target_link_libraries(hiop_math INTERFACE OpenMP::OpenMP_CXX)
```
causes cmake to crap out. If I comment the above line, everything works. The underlying issue is that I don't have C++ OpenMP libraries. But I have Fortran OpenMP, which seems to be enough since everything works. Do we really need to specifically use OpenMP_CXX?

**Comment by ashermancinelli** [comment]
I cleaned my history and cherry-picked the commits so that `plan/` is removed from the history. Sorry about that!

**Comment by cnpetra** [comment]
my bad, I should have move it from the gitlab hiop

**Comment by ashermancinelli** [comment]
I should never have used the openmpi-specific package, the latest commit should fix this.

**Comment by cnpetra** [comment]
be aware, OpenMP not the same OpenMPI

**Comment by ashermancinelli** [comment]
ahh, I see. I thought `OpenMP_CXX` only referred to the cpp bindings, but I guess I was wrong.

**Comment by ashermancinelli** [comment]
I think [this link](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenMP.cmake#L56) indicates that the 'cxx' in `OpenMP_CXX` only refers to the language openmp will be used from. Very odd that it would cause problems in your build.

**Comment by ashermancinelli** [comment]
@cnpetra Does the most recent build still fail on your machine?

**Pull request merged**
