### PR TITLE
Fix compilation error when KLU is missing

### LINKED ISSUE #473: compilation error when klu is missing
```
/ccs/home/cpetra/work/projects/hiop/src/LinAlg/hiopLinSolverSparseCUSOLVER.hpp:64:10: fatal error: klu.h: No such file or directory
   64 | #include "klu.h"
```

### PR DESCRIPTION
**Pull request by pelesh**
CMake configuration was causing compilation error when cuSOLVER LU was enabled, but its KLU dependency was missing. This PR fixes it by not trying to build cuSOLVER LU module when KLU can't be found.

Fixes #473

### CODE REVIEW

**Comment by cnpetra** [comment]
just a quick comment: you need to leave `HIOP_USE_CUSOLVER` in place (needed for cuSOLVER cholesky) and add `HIOP_USE_CUSOLVER_LU` for cuSOLVER LU.

**Comment by cnpetra** [comment]
also, NlpSparseEx2 runs both Cholesky and LU solvers from cuSOLVER if I recall correctly and we need to differentiate now between the two.

**Comment by pelesh** [comment]
> just a quick comment: you need to leave `HIOP_USE_CUSOLVER` in place (needed for cuSOLVER cholesky) and add `HIOP_USE_CUSOLVER_LU` for cuSOLVER LU.

You really don't need `HIOP_USE_CUSOLVER` because it is available whenever CUDA is available. Option `HIOP_USE_CUSOLVER` was added because additional configuration was needed to use LU factorization from cuSOLVER library (namely KLU symbolic factorization was needed). Cholesky and QR factorizations in cuSOLVER run out of box when `HIOP_USE_CUDA` is selected, so you don't need additional option to enable them.

**Comment by pelesh** [comment]
> just a quick comment: you need to leave `HIOP_USE_CUSOLVER` in place (needed for cuSOLVER cholesky) and add `HIOP_USE_CUSOLVER_LU` for cuSOLVER LU.

You really don't need `HIOP_USE_CUSOLVER` because it is available whenever CUDA is available. Option `HIOP_USE_CUSOLVER` was added because additional configuration was needed to use LU factorization from cuSOLVER library (namely KLU symbolic factorization was needed). Cholesky and QR factorizations in cuSOLVER run out of box when `HIOP_USE_CUDA` is selected, so you don't need additional option to enable them.

**Comment by cnpetra** [comment]
> > just a quick comment: you need to leave `HIOP_USE_CUSOLVER` in place (needed for cuSOLVER cholesky) and add `HIOP_USE_CUSOLVER_LU` for cuSOLVER LU.
> 
> You really don't need `HIOP_USE_CUSOLVER` because it is available whenever CUDA is available. Option `HIOP_USE_CUSOLVER` was added because additional configuration was needed to use LU factorization from cuSOLVER library (namely KLU symbolic factorization was needed). Cholesky and QR factorizations in cuSOLVER run out of box when `HIOP_USE_CUDA` is selected, so you don't need additional option to enable them.

ok, sounds like a good idea to drop it

**Review by cnpetra — CHANGES_REQUESTED** [review]

**Review by cnpetra — APPROVED** [review]

**Pull request merged**
