### PR TITLE
Fix for double pipeline trigger

### PR DESCRIPTION
**Pull request by ashermancinelli**
PNNL CI would trigger two jobs, the first of which would always fail. Should be fixed here 

CC @GitBytes @pelesh

### CODE REVIEW

**Comment by ashermancinelli** [comment]
@cnpetra you brought up that the full build matrix job leaves the PNNL jobs showing as 'blocked'. I think I can remove this in the same PR.

**Comment by pelesh** [comment]
> @cnpetra you brought up that the full build matrix job leaves the PNNL jobs showing as 'blocked'. I think I can remove this in the same PR.

This was my pet peeve, too. Thanks for fixing this @ashermancinelli!

**Comment by ashermancinelli** [comment]
Alright, the full build matrix will no longer stop the pipeline from showing as 'blocked':

image

In addition, you can manually run all 32 jobs or a particular subset of the full build matrix from the ui:

Screen Shot 2020-12-29 at 2 36 11 PM

The weekly run of all configurations will remain the same.

**Comment by ashermancinelli** [comment]
@cnpetra I believe this is ready for review/merge

**Pull request merged**
