### PR TITLE
Add paths to COINHSL to build script

### PR DESCRIPTION
**Pull request by ashermancinelli**
Builds with optional dependency COINHSL in our build script.

CC @pelesh @nychiang

### CODE REVIEW

**Comment by pelesh** [comment]
@nychiang, could you please push fix to #110 to `sparse-develop`? We need to rebase this to the fixed `sparse-develop` to make this work.

**Comment by nychiang** [comment]
> @nychiang, could you please push fix to #110 to `sparse-develop`? We need to rebase this to the fixed `sparse-develop` to make this work.

sure. Will use the code you mentioned in #120

**Comment by pelesh** [comment]
This PR would enable regression tests with sparse solver MA57, including examples 6 and 7. They run correctly on newell, marianas and ascent pipelines.

@cnpetra, I think this can be merged.

**Review by pelesh — APPROVED** [review]

**Comment by ashermancinelli** [comment]
FYI This has been rebased on top of sparse-develop

**Comment by cnpetra** [comment]
@ashermancinelli : sorry, I forgot to merge this. will try to rebase on develop.

**Review by pelesh — CHANGES_REQUESTED** [review]
@ashermancinelli I think this needs to be rebased to `develop` (or since the changes are minimal new PR needs to be created).

**Comment by ashermancinelli** [comment]
I'll rebase to develop, thanks for pointing this out.

**Comment by ashermancinelli** [comment]
This should be good to go now

**Review by pelesh — APPROVED** [review]

**Pull request merged**
