### PR TITLE
Add status to determine of factorization was successful or not

### PR DESCRIPTION
**Pull request by fritzgoebel**
Fixes https://github.com/LLNL/hiop/issues/469 for now.

I put in a solution to the sparse example 2 failure when using ginkgo. It adds a simple check to the factorization code returning a status of -1 if the lower right corner of the U factor is 0, NaN or inf.

For the fix to work, the updated [GLU integration branch](https://github.com/ginkgo-project/ginkgo/tree/glu) of Ginkgo has to be used.

Please note that this is a temporary solution and the check I put in is very simple. The interface to get information about the success of a factorization from Ginkgo might change at a later point.

### CODE REVIEW

**Comment by fritzgoebel** [comment]
Yes, on a V100 on Summit the sparse test 2 now passes. I pushed the fix to the same ginkgo branch that was used before, so the update should be not much effort.

**Comment by pelesh** [comment]
@ashermancinelli, we need to update Ginkgo modules on all CI pipelines, so we can test this branch.

**Review by pelesh — APPROVED** [review]
Looks good to me. The merge should be on hold until CI pipeline is updated with new Ginkgo version and all tests for this branch pass.

**Comment by pelesh** [comment]
CC @nkoukpaizan

**Comment by CameronRutherford** [comment]
I have pushed updates to the Newell and Marianas environment for this branch. Marianas seems to be building fine, but Newell is generating an issue when compiling:

<details>
<summary>
Compiler Error Output
</summary>

```
[  3%] Built target hiopUtils
[  4%] Built target hiopInterface
[ 15%] Built target hiopOptimization
[ 16%] Building CXX object src/LinAlg/CMakeFiles/hiopLinAlg.dir/hiopLinSolverSparseGinkgo.cpp.o
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp: In function ‘std::shared_ptr<gko::matrix::Csr<double, int> > hiop::{anonymous}::transferTripletToCSR(std::shared_ptr<gko::Executor>, int, hiop::hiopMatrixSparse*, int**, int**)’:
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:179:89: warning: narrowing conversion of ‘n_’ from ‘int’ to ‘gko::dim<2>::dimension_type {aka long unsigned int}’ inside { } [-Wnarrowing]
     auto mtx = gko::share(gko::matrix::Csr<double, int>::create(exec, gko::dim<2>{n_, n_}, val_array, col_idxs, row_ptrs));
                                                                                         ^
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp: In member function ‘virtual int hiop::hiopLinSolverSymSparseGinkgo::matrixChanged()’:
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:288:28: error: ‘using element_type = const class gko::preconditioner::Ilu<> {aka const class gko::preconditioner::Ilu<>}’ has no member named ‘get_status’; did you mean ‘get_size’?
     auto status = precond->get_status();
                            ^~~~~~~~~~
                            get_size
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp: In member function ‘virtual bool hiop::hiopLinSolverSymSparseGinkgo::solve(hiop::hiopVector&)’:
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:308:74: warning: narrowing conversion of ‘((hiop::hiopLinSolverSymSparseGinkgo*)this)->hiop::hiopLinSolverSymSparseGinkgo::n_’ from ‘int’ to ‘gko::dim<2>::dimension_type {aka long unsigned int}’ inside { } [-Wnarrowing]
     auto dense_x = gko::matrix::Dense<double>::create(exec_, gko::dim<2>{n_, 1}, gko::Array<double>::view(exec_, n_, dx), 1);
                                                                          ^~
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:309:74: warning: narrowing conversion of ‘((hiop::hiopLinSolverSymSparseGinkgo*)this)->hiop::hiopLinSolverSymSparseGinkgo::n_’ from ‘int’ to ‘gko::dim<2>::dimension_type {aka long unsigned int}’ inside { } [-Wnarrowing]
     auto dense_b = gko::matrix::Dense<double>::create(exec_, gko::dim<2>{n_, 1}, b_array, 1);
                                                                          ^~
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp: In member function ‘virtual int hiop::hiopLinSolverNonSymSparseGinkgo::matrixChanged()’:
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:372:28: error: ‘using element_type = const class gko::preconditioner::Ilu<> {aka const class gko::preconditioner::Ilu<>}’ has no member named ‘get_status’; did you mean ‘get_size’?
     auto status = precond->get_status();
                            ^~~~~~~~~~
                            get_size
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp: In member function ‘virtual bool hiop::hiopLinSolverNonSymSparseGinkgo::solve(hiop::hiopVector&)’:
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:392:74: warning: narrowing conversion of ‘((hiop::hiopLinSolverNonSymSparseGinkgo*)this)->hiop::hiopLinSolverNonSymSparseGinkgo::n_’ from ‘int’ to ‘gko::dim<2>::dimension_type {aka long unsigned int}’ inside { } [-Wnarrowing]
     auto dense_x = gko::matrix::Dense<double>::create(exec_, gko::dim<2>{n_, 1}, x_array, 1);
                                                                          ^~
/people/ruth521/projects/hiop/hiop-git/src/LinAlg/hiopLinSolverSparseGinkgo.cpp:393:74: warning: narrowing conversion of ‘((hiop::hiopLinSolverNonSymSparseGinkgo*)this)->hiop::hiopLinSolverNonSymSparseGinkgo::n_’ from ‘int’ to ‘gko::dim<2>::dimension_type {aka long unsigned int}’ inside { } [-Wnarrowing]
     auto dense_b = gko::matrix::Dense<double>::create(exec_, gko::dim<2>{n_, 1}, b_array, 1);
                                                                          ^~
make[2]: *** [src/LinAlg/CMakeFiles/hiopLinAlg.dir/hiopLinSolverSparseGinkgo.cpp.o] Error 1
make[1]: *** [src/LinAlg/CMakeFiles/hiopLinAlg.dir/all] Error 2
make: *** [all] Error 2
```

</details>

I found that I couldn't build with a GCC newer than 8 on Marianas, so perhaps I have to re-build the Newell environment.

**Comment by pelesh** [comment]
> I have pushed updates to the Newell and Marianas environment for this branch. Marianas seems to be building fine, but Newell is generating an issue when compiling:
> 

The error you see on Newell suggests that Ginkgo was not built from the most recent `glu` branch. The old API does not recognize `status()` method. Perhaps Ginkgo module needs to be rebuilt on Newell?

**Comment by fritzgoebel** [comment]
Yes, indeed it looks like @pelesh is correct, the `get_status` is what I added in ginkgo to make this work. If you build the newest version of the ginkgo branch this should be fine.

**Comment by cnpetra** [comment]
are the CIs ready for this to be merged?

**Comment by pelesh** [comment]
> are the CIs ready for this to be merged?

I believe @CameronRutherford is about to update Ginkgo installation on marianas and newell and update build scripts accordingly. After he pushes those changes and tests pass, it will be safe to merge.

Note that tests on ascent already pass.

**Comment by pelesh** [comment]
Marianas pipeline was fixed in [86346cc](https://github.com/LLNL/hiop/pull/472/commits/86346ccd0d691b87f8846e3419b2b61670b55416); all tests passed.

@cnpetra, this is ready to merge.

**Pull request merged**
