### PR TITLE
Add Eigen submodule and buildsystem support

### PR DESCRIPTION
**Pull request by pelesh**
This is a draft PR to discuss how to add Eigen support to HiOp. Some things to decide:
- [x] Where to add third-party submodules in HiOp source?
- [x] What version/tag of Eigen to use?
 
Addresses two of the three action items of #434

### CODE REVIEW

**Comment by ashermancinelli** [comment]
I chose `tpl/` as the directory because that's what [our key dependencies use](https://github.com/LLNL/RAJA/tree/develop/tpl). Version of Eigen is up to @cnpetra . Thanks for opening!

**Comment by cnpetra** [comment]
`tpl/` seems a sensible choice

and let's go with version 3.4.0

**Comment by cnpetra** [comment]
make sure you mark this PR as "Ready for review" when done

**Comment by pelesh** [comment]
> make sure you mark this PR as "Ready for review" when done

`git submodule update --init` will get you Eigen 3.4.0 source in `tpl/eigen` directory. Thanks, @ashermancinelli.

**Review by cnpetra — APPROVED** [review]

**Review by ashermancinelli — APPROVED** [review]

**Pull request merged**
