### PR TITLE
Gitlab pipeline refactor

### PR DESCRIPTION
**Pull request by CameronRutherford**
This will be the first of a few PRs to upgrade HiOp CI. This is just a refactor, but should be merged before we start debugging further. This refactor also breaks existing CI, and so it's a high priority to get this fixed and merged first before working on other features.

This PR separates each GitLab CI yaml into separate files, and prepares to implement posting of status from PNNL and ORNL GitLab to HiOp GitHub.

@nychiang you will have to go on to LLNL GitLab, and re-configure where CI looks for pipeline configuration. This should be in Settings -> CI/CD Settings -> General Pipelines -> CI/CD Configuration File. Just specify `.gitlab/llnl-ci.yml` as the file, and CI should be up and running again in this PR and future pipelines once people rebase.

This might break existing pipelines, and so we should merge and rebase this to get CI back online for other developers.

### CODE REVIEW

**Comment by CameronRutherford** [comment]
@nychiang you will also probably also have to re-trigger the pipeline for this branch if you were unable to get to this before the mirror was updated.

IMO we should also re-factor the LLNL configuration - if you make it so that your GitLab repo becomes a push mirror, you will get CI to trigger much faster. This is currently how PNNL CI is configured and would be in line with how I am going to deploy ORNL CI.

**Comment by nychiang** [comment]
@CameronRutherford I just updated CI configurations on LLNL gitlab. Can you push some changes to this branch and see if my change works?

**Comment by CameronRutherford** [comment]
>

> @CameronRutherford I just updated CI configurations on LLNL gitlab. Can you push some changes to this branch and see if my change works?

I added an empty commit. Because you have a pull mirror, it will take a while for the pull mirror to update, and then the pipeline status will show up.

While I want to change to a push mirror to fix this, you can also try and debug the integration by manually updating the pull mirror, and running the pipeline manually if necessary. I would also recommend opening the pipeline in the pipeline editor on your GitLab in case there are any syntax issues that I introduced.

**Comment by CameronRutherford** [comment]
@nychiang looks like LLNL CI is now running and failing - something you can fix by looking at the job logs?

**Review by nychiang — APPROVED** [review]
LGTM. @CameronRutherford and I just did a quick test on LLNL gitlab and everything works fine. Cheers!

**Pull request merged**
