### PR TITLE
Update umpire version to 5.0.1

### PR DESCRIPTION
**Pull request by ashermancinelli**

### CODE REVIEW

**Comment by nychiang** [comment]
Which version of cmake should we use? >3.18? I saw you removed the line to load module cmake 3.19 from newell.

**Comment by nychiang** [comment]
@ashermancinelli This branch has some conflicts. Can you apply your changes to the latest develop branch?

**Comment by cnpetra** [comment]
lgtm and will merge as soon as the conflicts will be fixed (they are caused by the removal of a commit (sparse gpu kernels) from the develop)

**Comment by ashermancinelli** [comment]
I see - I'll resolve this conflicts today

**Comment by ashermancinelli** [comment]
> @ashermancinelli This branch has some conflicts. Can you apply your changes to the latest develop branch?

3.18 should be fine I think - we just have a newer cmake module on newell and I went ahead and built a newer cmake on some of the other platforms.

**Review by cnpetra — APPROVED** [review]

**Comment by ashermancinelli** [comment]
I don't have merge permissions, so merge whenever you're ready @cnpetra

**Pull request merged**
