### PR TITLE
Removing legacy build script

### PR DESCRIPTION
**Pull request by ashermancinelli**
I don't think we need the old build script. @pelesh If you approve we can merge and continue with #117.

### CODE REVIEW

**Comment by GitBytes** [comment]
This will Fix #114 as well.

**Review by pelesh — APPROVED** [review]

**Comment by cnpetra** [comment]
ready to merge?

**Comment by pelesh** [comment]
Yes, we can merge. The `build.sh` script was supposed to automate tests outlined in `README_developer.md`, but it didn't work as expected. We can remove it to avoid confusion.

**Comment by cnpetra** [comment]
> Yes, we can merge. The `build.sh` script was supposed to automate tests outlined in `README_developer.md`, but it didn't work as expected. We can remove it to avoid confusion. It is not used anymore.

oh, I see.

**Pull request merged**
