### PR TITLE
Full build matrix dev

### LINKED ISSUE #132: No automated builds of many configuration options
We currently automate a small subset of possible hiop builds, each with GCC 7 or similar release.

- PNNL CI uses BUILD.sh script with all options enabled
- ORNL CI uses BUILD.sh script with all options enabled
- Github actions build uses default cmake build with most options disabled

Because of how few of the possible configurations we test with, we've had numerous issues (eg #46, #47,  #121).

Following discussion, these are completion criteria:

- [x] weekly/nightly long build
- [x] cmake option for running valgrind on integration tests

### LINKED ISSUE #145: System-specific code in Build Script
After reviewing CI configuration for the Q1 deliverables, I think all the system-specific code in BUILD.sh makes adding another platform quite difficult. We'll be adding more CI platforms moving forward, so this should be a priority. Also, I believe ORNL team recommended against platform-specifics in the build script. @pelesh can you confirm?

### PR DESCRIPTION
**Pull request by ashermancinelli**
Please review, as this may be way out of scope. It seems like we keep encountering erroneous build configurations and this is in line with Q1 deliverables, so this seems needed.

- Enables manually-triggered build of all sensible CMake configurations
- Refactors out most system-specifics from BUILD.sh
- Enables optional valgrind tests (@cnpetra please advise which exe's you'd like to run valgrind on)

Displays a CSV report of all builds at the end of the run, [see here for example](https://gitlab.pnnl.gov/exasgd/solvers/hiop-mirror/-/jobs/18930). Right now this only *builds* every configuration (16 in total), but doesn't run all tests, although I have an option for that.

Example final report from linked run:

```
buildID;buildStatus;cmakeOptions
0;Success; -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DHIOP_DEEPCHECKS=ON -DHIOP_USE_RAJA=OFF -DHIOP_USE_GPU=OFF -DHIOP_WITH_KRON_REDUCTION=ON -DHIOP_METIS_DIR=/share/apps/metis/5.1.0 -DHIOP_UMFPACK_DIR=/qfs/projects/exasgd/newell/suitesparse -DHIOP_USE_MPI=ON
1;Success; -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DHIOP_DEEPCHECKS=ON -DHIOP_USE_RAJA=OFF -DHIOP_USE_GPU=OFF -DHIOP_WITH_KRON_REDUCTION=ON -DHIOP_METIS_DIR=/share/apps/metis/5.1.0 -DHIOP_UMFPACK_DIR=/qfs/projects/exasgd/newell/suitesparse -DHIOP_USE_MPI=OFF
2;Success; -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DHIOP_DEEPCHECKS=ON -DHIOP_USE_RAJA=OFF -DHIOP_USE_GPU=OFF -DHIOP_WITH_KRON_REDUCTION=OFF -DHIOP_USE_MPI=ON
...
```

Resolves #132
Resolves #145

### CODE REVIEW

**Comment by pelesh** [comment]
All tests pass and the test configuration structure is more modular, what makes it easier to add new pipelines. 

It is not quite clear to me what is the purpose of the manually triggered build of all CMake configurations. It runs only builds, but not tests. Was the intention to test the build system only?

**Comment by ashermancinelli** [comment]
No, enabling the tests works as well, it just takes a very long time. I planned on enabling tests and setting up a weekly build if everyone checked off on the pr.

**Review by pelesh — APPROVED** [review]
Looks great!

**Comment by cnpetra** [comment]
@ashermancinelli : at minimum, valgrind on ex1 and ex4

**Comment by ashermancinelli** [comment]
@cnpetra Any suggestions for the valgrind options we use besides these?
```
         --leak-check=full
         --show-leak-kinds=all
         --track-origins=yes
         --verbose
```

Also, should any errors/warnings trigger a failure in CI? Lots of the warnings

**Comment by ashermancinelli** [comment]
I rebased on develop. Here's an example of the tests running as well: https://gitlab.pnnl.gov/exasgd/solvers/hiop-mirror/-/jobs/19086

**Comment by ashermancinelli** [comment]
@cnpetra If you'd like to review the valgrind tests, I think this is otherwise ready for merging.

**Comment by cnpetra** [comment]
I think we should document this option in the readme file, ideally also in the tex usermanual

**Comment by ashermancinelli** [comment]
@cnpetra I've added notes in the readme and tex documentation. [See this pipeline](https://gitlab.pnnl.gov/exasgd/solvers/hiop-mirror/-/jobs/19142) for an example run building/testing all 32 configurations. Unless you have anything else, I think this is ready.

**Comment by cnpetra** [comment]
lgtm

**Review by cnpetra — APPROVED** [review]

**Pull request merged**
