### PR TITLE
switching memcpy for std::rotate

### PR DESCRIPTION
**Pull request by ashermancinelli**
Please find #37

### CODE REVIEW

**Comment by cnpetra** [comment]
I am pretty sure your update is not going to work (you're rotating pointers to columns). `std::rotate` is a good idea, however, it is slightly more expensive than what I had in mind. Will take another stab at the function, without memcpy (btw, the function works perfectly on all three OS I have).

**Comment by cnpetra** [comment]
is this working ?

https://github.com/LLNL/hiop/commit/aa77c056d28b159f296b93db3d0291aeaf9a8029

**Comment by cnpetra** [comment]
works on mac and ubuntu

**Comment by ashermancinelli** [comment]
I see, you're right about my std::rotate method. My confusion about the current method however. Given a matrix A:
```c++
| 2 2 2 |
| 1 1 1 |
| 1 1 1 |
```
calling `A.shiftRows(2);` results in:
```c++
| 2 2 2 |
| 1 1 1 |
| 2 2 2 |
```
Where I expected this:
```c++
| 1 1 1 |
| 1 1 1 |
| 2 2 2 |
```
Is this behavior intended?

**Comment by ashermancinelli** [comment]
Moving discussion to the issue now that we established the infeasibility of the PR.

**Pull request closed without merging**
