### PR TITLE
Removed incorrectly included header

### PR DESCRIPTION
**Pull request by ashermancinelli**
See #47

### CODE REVIEW

**Comment by cnpetra** [comment]
fixed the header problem, but still does not compile

```
[ 86%] Building CXX object tests/CMakeFiles/testMatrix.dir/testMatrix.cpp.o
In file included from /ccs/home/cpetra/work/projects/hiop/tests/LinAlg/matrixTests.hpp:65:0,
                 from /ccs/home/cpetra/work/projects/hiop/tests/LinAlg/matrixTestsDense.hpp:59,
                 from /ccs/home/cpetra/work/projects/hiop/tests/testMatrix.cpp:61:
/ccs/home/cpetra/work/projects/hiop/tests/LinAlg/testBase.hpp:85:15: error: expected '{' before '::' token
 namespace hiop::tests
```

**Comment by ashermancinelli** [comment]
Ah yes, we had to resolve this in another internal branch. It seems that even with the c++11 flags, gcc/7.4.0 will tolerate nested namespaces. nvcc and others do not.

**Comment by cnpetra** [comment]
gnu 4.8.5

**Comment by ashermancinelli** [comment]
I've tested with gcc 4.8.5, 5.2.0, and 7.4.0. Testing with 8.3, 9.1, and 10.1 by the end of the day just to be sure.

**Comment by ashermancinelli** [comment]
I believe this is ready for merge.

**Comment by ashermancinelli** [comment]
Closing in favor of more comprehensive PR.

**Pull request closed without merging**
