### PR TITLE
fix x vector dimension error

### PR DESCRIPTION
**Pull request by jwang125**
Fixing issue mention here https://github.com/LLNL/hiop/issues/284.

### CODE REVIEW

**Comment by nychiang** [comment]
I saw you add more changes to the code. For example, change `local_data_host` to `local_data` in several places, and modify the function `step_size_inf`. Will HiOp still reach FR in the recourse problem after you change these?
I don't know why the previous assertion error disappears after these changes.

**Review by nychiang — COMMENTED** [review]
Will these changes introduce new problem to the exago small examples (9 or 118 system)?

**Comment by jwang125** [comment]
step_size_inf was wrong. Wanted to change a long time ago because was measuring |x-x_0|^2 which have different lengths and thus always returns inf. I'm not sure why the error disappeared. Could be updated develop. But develop has the error you saw.

**Comment by jwang125** [comment]
The smaller tests seem to suffer the same error now with create_Vector function which throws an umpire exception. Testing to see if the new added lines caused this or was a problem with develop.

**Comment by jwang125** [comment]
I have confirmed that if I only implement the one line, the error in create_Vector comes up as well. And it's from hiopInterfacePrimalDecomp. This means there's more than one error with the latest develop.

grad_r =LinearAlgebraFactory::create_vector(master_prob_->get_mem_space(), nc_) ;

I could go back to this one update for this branch if that's better. Then we can try to fix this next error.

**Comment by cnpetra** [comment]
@jwang125 : currently, the hiopInterfacePrimalDecomp (and its classes) and hiopAlgPrimalDecomp have memory space hardcoded as "default". I think this may be the root cause for the umpire exceptions and other nasty things you're seeing with exago. 

I am working on a PR that will allow to change the memory space for PriDec solver (and master solver). 

@nychiang suggested to try to changes the hardcoded "default" memory space to "um" in PriDec interface and Alg and see if that's working with exago.

**Comment by cnpetra** [comment]
@jwang125 sorry for the bugs I introduced with alloc_clone :(

**Comment by jwang125** [comment]
Yes I am looking at the code and I agree that's why. It's also because a bad code I gave Shri a while ago that createsa a new RecourseApproxEvaluator each time set_recourse_approx_evaluator is called. And he has that in the exago code. This might explain why ex9 doesn't fail because I've changed that in ex9, which does call the constructor.

**Comment by jwang125** [comment]
Hi guys, I think the issue is less with "DEFAULT" but more with the constructor for 

RecourseApproxEvaluator(const int nc,
                        const int S,
                        const double& rval,
                        const hiopVector& rgrad,
                        const hiopVector& rhess,
                        const hiopVector& x0)
which didn't define mem_space_ so it was not assigned any value. Once this is fixed, I'm back to previous known errors! If you're OK with this I will maintain changes on step_size_inf, modify this constructor and push and do this PR. Then we can look at the older known bugs.

**Review by cnpetra — APPROVED** [review]

**Comment by cnpetra** [comment]
> Yes I am looking at the code and I agree that's why. It's also because a bad code I gave Shri a while ago that creates a a new RecourseApproxEvaluator each time set_recourse_approx_evaluator is called. And he has that in the exago code. This might explain why ex9 doesn't fail because I've changed that in ex9, which doesn't call the constructor.

user is not supposed to create `RecourseApproxEvaluator `, only to evaluate it ... Ex8 is still doing this.

**Pull request merged**
