### PR TITLE
GPU Inertia Correction fix

### PR DESCRIPTION
**Pull request by cnpetra**
proposes an approach for computing inertia when running on GPU via MAGMA

this approach is supposed to be numerically stable.  Performance issues will be revisited as we iterate with magma team on a couple of details.

With this fix, HiOp-GPU should pass all tests that HiOp-CPU passes.

### CODE REVIEW

**Comment by pelesh** [comment]
Is this still using Magma release or you need Magma from a development branch?

**Comment by pelesh** [comment]
All tests shipped with HiOp pass on Power9/V100.

**Comment by cnpetra** [comment]
> Is this still using Magma release or you need Magma from a development branch?

magma release

**Comment by cnpetra** [comment]
> All HiOp tests pass on Power9/V100.
> 
> System/build description:
> 
> ```
> $ module list
> Currently Loaded Modulefiles:
>   1) gcc/7.4.0              3) cmake/3.17.2           5) ipopt/3.13.0           7) metis/5.1.0
>   2) cuda/10.2              4) openmpi/3.1.5          6) magma/2.5.2_cuda10.2
> ```
> 
> UMFPACK was built locally from SuiteSparse source v5.7.2, and OpenBLAS 0.3.3 was available as rpm package.
> 
> Options `HIOP_USE_GPU` and `HIOP_WITH_KRON_REDUCTION` were set to `On`.

same on intel Xeon/V100. Surprised to see it passes all test. Peak performance with the GPU flooded not too bad, 18-20%

**Pull request merged**
