### PR TITLE
Intvec refactor

### PR DESCRIPTION
**Pull request by ashermancinelli**
Closes: #247 
Closes: #243

* Removes `operator[]`
* Adds syncing methods to abstract interface

### CODE REVIEW

**Comment by nychiang** [comment]
I think we should wait for PR #242.

**Comment by cnpetra** [comment]
> I think we should wait for PR #242.

PR #242 merged in develop, please rebase @ashermancinelli this should help with passing the tests.

**Comment by ashermancinelli** [comment]
Sounds good, I updated hiopVectorInt to look more like hiopVector offline. I'll rebase and leave a comment here when it's done.

**Comment by ashermancinelli** [comment]
After looking at most recent develop branch, I'm thinking I should just remove `operator[]` and update the rest of the codebase. This is probably best done in a new PR. Thoughts? @cnpetra @nychiang

**Comment by nychiang** [comment]
According to the other discussions/branches, I think `operator[]` should be replaced by member accessors.
I am fine if you want to close this PR and start a new one, or just modify the descriptions/title of this PR. It's up to you.

**Pull request closed without merging**
