### PR TITLE
checking for cmake >= 12 before setting policy introduced in that release

### PR DESCRIPTION
**Pull request by ashermancinelli**
Please see #46

### CODE REVIEW

**Comment by cnpetra** [comment]
looks like it does not fix the issue

cmake's GREATER_EQUAL does not work as you think it does. Apparently, it performs string comparison, meaning (cmake version) 3.9.2 > 3.11.2

**Comment by pelesh** [comment]
@ashermancinelli the correct fix is to check if the policy is defined, not to check for CMake version. See my comment in #46.

**Comment by ashermancinelli** [comment]
I've built with every version of gcc and cmake we have on newell. I'll have to build some older versions of cmake manually to test below cmake 12.1.

**Comment by ashermancinelli** [comment]
closing as per offline conversation.

**Comment by ashermancinelli** [comment]
Closing in favor of more comprehensive PR.

**Pull request closed without merging**
